version: '3'
services: 
    db:
        image: postgres:10.5-alpine
        ports: 
            - 54321:5432
        environment: 
            POSTGRES_PASSWORD: password
    server:
        build: .
        links: 
            - db:db
        ports: 
            - 8088:8088
        # container_name: user_db
        environment: 
            DATABASE_URL: 'postgres://postgres:password@db:5432/postgres?sslmode=disable'
            DATA_DIRECTORY: '/go/src/github.com/andodeki/code/HA/api.gridbackendapp.com'


            # finance_postgres
